#!/usr/bin/env node

/**
 * Sloth Voice Server Setup Wizard
 * Interactive first-run configuration for non-technical users.
 */

const fs = require("fs");
const path = require("path");
const readline = require("readline");
const crypto = require("crypto");
const { execSync } = require("child_process");

const ENV_PATH = path.join(__dirname, "..", ".env");
const ENV_EXAMPLE_PATH = path.join(__dirname, "..", ".env.example");

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(prompt, defaultValue = "") {
  return new Promise((resolve) => {
    const displayPrompt = defaultValue
      ? `${prompt} (${defaultValue}): `
      : `${prompt}: `;
    rl.question(displayPrompt, (answer) => {
      resolve(answer.trim() || defaultValue);
    });
  });
}

function questionYesNo(prompt, defaultYes = true) {
  return new Promise((resolve) => {
    const hint = defaultYes ? "[Y/n]" : "[y/N]";
    rl.question(`${prompt} ${hint}: `, (answer) => {
      const a = answer.trim().toLowerCase();
      if (!a) return resolve(defaultYes);
      resolve(a === "y" || a === "yes");
    });
  });
}

function generateSecret() {
  return crypto.randomBytes(32).toString("hex");
}

function checkPortAvailable(port) {
  try {
    const result = execSync(
      `node -e "const net = require('net'); const s = net.createServer(); s.once('error', () => process.exit(1)); s.listen(${port}, () => { s.close(); process.exit(0); })"`,
      { timeout: 5000, stdio: "pipe" }
    );
    return true;
  } catch {
    return false;
  }
}

async function main() {
  console.log("\n🦥  Sloth Voice Server Setup\n");
  console.log("This wizard will help you configure your server.\n");

  const envExists = fs.existsSync(ENV_PATH);

  if (envExists) {
    const overwrite = await questionYesNo(
      "A .env file already exists. Overwrite it?",
      false
    );
    if (!overwrite) {
      console.log("\nSetup cancelled. Your existing configuration was preserved.");
      rl.close();
      return;
    }
  }

  let template = "";
  if (fs.existsSync(ENV_EXAMPLE_PATH)) {
    template = fs.readFileSync(ENV_EXAMPLE_PATH, "utf-8");
  }

  console.log("\n--- Server Configuration ---\n");

  const serverName = await question("Server name", "My Sloth Voice Server");
  const serverDescription = await question("Server description (optional)", "");
  const serverPort = await question("HTTP port", "5000");
  const serverPassword = await question("Server password (leave empty for open access)", "");

  console.log("\n--- Network Configuration ---\n");

  const upnpEnabled = await questionYesNo(
    "Enable UPnP for automatic port forwarding? (recommended for home hosting)",
    true
  );

  const publicAddress = await question(
    "Public IP address (leave empty for auto-detection)",
    ""
  );

  const rtcMinPort = await question("Voice UDP port range start", "40000");
  let rtcMaxPort = await question("Voice UDP port range end", "40099");

  const minPort = parseInt(rtcMinPort, 10);
  let maxPort = parseInt(rtcMaxPort, 10);
  if (maxPort - minPort > 100) {
    console.log("\n⚠️  Port range larger than 100. Clamping to 100 ports for UPnP compatibility.");
    maxPort = minPort + 99;
  }

  console.log("\n--- Generating Configuration ---\n");

  const jwtSecret = generateSecret();
  console.log("✓ Generated JWT secret");

  const isPortAvailable = checkPortAvailable(parseInt(serverPort, 10));
  if (isPortAvailable) {
    console.log(`✓ Port ${serverPort} is available`);
  } else {
    console.log(`⚠️  Port ${serverPort} appears to be in use. Make sure to free it before starting.`);
  }

  console.log("\n--- Writing Configuration ---\n");

  const envContent = `# Generated by sloth-voice setup wizard
# ${new Date().toISOString()}

# ─── General ──────────────────────────────────────────────────────────────────

SERVER_PORT=${serverPort}
SERVER_NAME=${serverName}
${serverDescription ? `SERVER_DESCRIPTION=${serverDescription}` : "# SERVER_DESCRIPTION="}
${serverPassword ? `SERVER_PASSWORD=${serverPassword}` : "# SERVER_PASSWORD="}

# ─── Security ───────────────────────────────────────────────────────────────────

# JWT secret - DO NOT SHARE THIS VALUE
JWT_SECRET=${jwtSecret}

# ─── Database ─────────────────────────────────────────────────────────────────

SERVER_DB_PATH=./server.db

# ─── WebRTC / Voice ─────────────────────────────────────────────────────────────

MEDIASOUP_LISTEN_IP=0.0.0.0
${publicAddress ? `PUBLIC_ADDRESS=${publicAddress}` : "# PUBLIC_ADDRESS= (auto-detect)"}

RTC_MIN_PORT=${minPort}
RTC_MAX_PORT=${maxPort}
IP_CHECK_INTERVAL=300
MEDIASOUP_LOG_LEVEL=warn
AUDIO_BITRATE_KBPS=64

# ─── STUN Servers (for NAT traversal) ───────────────────────────────────────────

STUN_SERVERS=stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302

# ─── UPnP / NAT port mapping ─────────────────────────────────────────────────

UPNP_ENABLED=${upnpEnabled}
UPNP_TTL=0
UPNP_RTC_MAX_PORTS=50

# ─── TURN Server (optional, for restrictive networks) ──────────────────────────

TURN_ENABLED=false
# TURN_URL=
# TURN_USERNAME=
# TURN_PASSWORD=
`;

  fs.writeFileSync(ENV_PATH, envContent);
  console.log("✓ Configuration written to .env");

  console.log("\n--- Summary ---\n");
  console.log(`  Server name:     ${serverName}`);
  console.log(`  HTTP port:       ${serverPort}`);
  console.log(`  Voice ports:     ${minPort}-${maxPort} (UDP)`);
  console.log(`  UPnP:            ${upnpEnabled ? "enabled" : "disabled"}`);
  console.log(`  Public IP:       ${publicAddress || "auto-detect"}`);
  console.log(`  Access:          ${serverPassword ? "password protected" : "open"}`);

  console.log("\n--- Next Steps ---\n");
  console.log("  1. Review the .env file if you want to make changes");
  console.log("  2. Run 'npm start' to start the server");
  console.log("  3. Connect with the Sloth Voice desktop client");
  console.log("");

  if (!publicAddress && upnpEnabled) {
    console.log("  ℹ️  UPnP is enabled. Your router should forward ports automatically.");
    console.log("      Your public IP will be detected automatically.\n");
  } else if (!publicAddress && !upnpEnabled) {
    console.log("  ⚠️  UPnP is disabled and no public IP was set.");
    console.log("      Make sure to manually configure port forwarding.\n");
  }

  rl.close();
}

main().catch((err) => {
  console.error("\n❌ Setup failed:", err.message);
  rl.close();
  process.exit(1);
});